<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
use \app\project\Uicomponent_Event_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Action_Model extends YZE_Model{
    use Action_Model_Method;
    
    const TYPE_OUTPUT = 'output';
    const TYPE_REDIRECT = 'redirect';
    const TYPE_POPUP = 'popup';
    const TYPE_CALL = 'call';
    const TYPE_WEBAPI = 'webapi';
    const TYPE_EMIT = 'emit';
    const TYPE_MUTATION = 'mutation';
    const TYPE_CLOSEPOPUP = 'closepopup';
    const TYPE_INTERVAL = 'interval';
    const REDIRECT_TYPE_INSIDE = 'inside';
    const REDIRECT_TYPE_OUTSIDE = 'outside';
    const REDIRECT_TYPE_UNSET = 'unset';
    const POPUP_TYPE_PAGE = 'page';
    const POPUP_TYPE_ALERT = 'alert';
    const POPUP_TYPE_UNSET = 'unset';
    const POPUP_PAGE_TYPE_PAGE = 'page';
    const POPUP_PAGE_TYPE_POPUP = 'popup';
    const POPUP_PAGE_TYPE_UNSET = 'unset';
    const BIND_CONDITION_TRUE = 'true';
    const BIND_CONDITION_FALSE = 'false';
    const TABLE= "action";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Action_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var enum
     */
    const F_TYPE = "type";
    /**
     * 
     * @var string
     */
    const F_REDIRECT = "redirect";
    /**
     * 
     * @var enum
     */
    const F_REDIRECT_TYPE = "redirect_type";
    /**
     * 
     * @var enum
     */
    const F_POPUP_TYPE = "popup_type";
    /**
     * 
     * @var string
     */
    const F_POPUPPAGEID = "popupPageId";
    /**
     * 
     * @var string
     */
    const F_CALL_UIID = "call_uiid";
    /**
     * 
     * @var string
     */
    const F_INPUT = "input";
    /**
     * 
     * @var string
     */
    const F_OUTPUT = "output";
    /**
     * 
     * @var integer
     */
    const F_BIND_API_ID = "bind_api_id";
    /**
     * 
     * @var enum
     */
    const F_POPUP_PAGE_TYPE = "popup_page_type";
    /**
     * 
     * @var string
     */
    const F_BIND_CLASS = "bind_class";
    /**
     * 
     * @var string
     */
    const F_BIND_UUID = "bind_uuid";
    /**
     * 绑定的条件
     * @var enum
     */
    const F_BIND_CONDITION = "bind_condition";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 
     * @var integer
     */
    const F_EMIT_EVENT_ID = "emit_event_id";
    /**
     * 
     * @var integer
     */
    const F_INDEX = "index";
    /**
     * 
     * @var integer
     */
    const F_INTERVAL_DURATION = "interval_duration";
    /**
     * 
     * @var integer
     */
    const F_INTERVAL_DELAY = "interval_delay";
    /**
     * 
     * @var string
     */
    const F_INTERVAL_ACTION = "interval_action";
    /**
     * 
     * @var string
     */
    const F_INTERVAL_COMPLETE = "interval_complete";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'type'       => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'output'],
      'redirect'   => ['type' => 'string', 'null' => false,'length' => '2995','default'	=> ''],
      'redirect_type' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'unset'],
      'popup_type' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'unset'],
      'popupPageId' => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'call_uiid'  => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'input'      => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'output'     => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'bind_api_id' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'popup_page_type' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'unset'],
      'bind_class' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'bind_uuid'  => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'bind_condition' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'true'],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'emit_event_id' => ['type' => 'integer', 'null' => true,'length' => '','default'	=> ''],
      'index'      => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'interval_duration' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'interval_delay' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'interval_action' => ['type' => 'string', 'null' => true,'length' => '145','default'	=> ''],
      'interval_complete' => ['type' => 'string', 'null' => true,'length' => '145','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_action_page1_idx',
  'emit_event_id' => 'fk_action_uicomponent_event1_idx',
  'bind_class' => 'bind_class',
  'bind_uuid' => 'bind_class',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
  'emit_event_id' => 
  array (
    'graphql_field' => 'emit_event',
    'target_class' => '\\app\\project\\Uicomponent_Event_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	private $emit_event;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Action_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	public function get_emit_event($suffix=null){
		if( ! $this->emit_event){
			$this->emit_event = Uicomponent_Event_Model::find_by_id($this->get(self::F_EMIT_EVENT_ID), $this->db, $suffix);
		}
		return $this->emit_event;
	}

	/**
	 * @return Action_Model
	 */
	public function set_emit_event(Uicomponent_Event_Model $new){
		$this->emit_event = $new;
		return $this;
	}

	
	public static function get_type(){
		return ['output','redirect','popup','call','webapi','emit','mutation','closepopup','interval'];
	}
	public static function get_redirect_type(){
		return ['inside','outside','unset'];
	}
	public static function get_popup_type(){
		return ['page','alert','unset'];
	}
	public static function get_popup_page_type(){
		return ['page','popup','unset'];
	}
	public static function get_bind_condition(){
		return ['true','false'];
	}

}?>