<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Action_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Mutation_Model extends YZE_Model{
    use Mutation_Model_Method;
    
    const TABLE= "mutation";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Mutation_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var string
     */
    const F_MUTATION_FROM_UUID = "mutation_from_uuid";
    /**
     * 
     * @var string
     */
    const F_MUTATION_DATA_ID = "mutation_data_id";
    /**
     * 
     * @var string
     */
    const F_MUTATION_DATA_NAME = "mutation_data_name";
    /**
     * 
     * @var string
     */
    const F_MUTATION_DATA_TYPE = "mutation_data_type";
    /**
     * 
     * @var integer
     */
    const F_ACTION_ID = "action_id";
    /**
     * 
     * @var string
     */
    const F_EXPRESSION = "expression";
    /**
     * 赋值操作符
     * @var string
     */
    const F_MUTATION_OPERATOR = "mutation_operator";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'mutation_from_uuid' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'mutation_data_id' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'mutation_data_name' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'mutation_data_type' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'action_id'  => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'expression' => ['type' => 'string', 'null' => false,'length' => '','default'	=> ''],
      'mutation_operator' => ['type' => 'string', 'null' => false,'length' => '45','default'	=> '='],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'action_id' => 'fk_mutation_action1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'action_id' => 
  array (
    'graphql_field' => 'action',
    'target_class' => '\\app\\project\\Action_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $action;
	
	public function get_action($suffix=null){
		if( ! $this->action){
			$this->action = Action_Model::find_by_id($this->get(self::F_ACTION_ID), $this->db, $suffix);
		}
		return $this->action;
	}

	/**
	 * @return Mutation_Model
	 */
	public function set_action(Action_Model $new){
		$this->action = $new;
		return $this;
	}

	

}?>