<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_Api_Action_Model extends YZE_Model{
    use Page_Bind_Api_Action_Model_Method;
    
    const MODE_SETTING = 'setting';
    const MODE_CODE = 'code';
    const TABLE= "page_bind_api_action";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_Api_Action_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 绑定关联的对象
     * @var string
     */
    const F_FROM_CLASS = "from_class";
    /**
     * 
     * @var string
     */
    const F_FROM_UUID = "from_uuid";
    /**
     * 
     * @var string
     */
    const F_OUTPUT_DATA_ID = "output_data_id";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 
     * @var enum
     */
    const F_MODE = "mode";
    /**
     * 
     * @var string
     */
    const F_CODE = "code";
    /**
     * 
     * @var string
     */
    const F_EXPRESSION = "expression";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'from_class' => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'from_uuid'  => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'output_data_id' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'mode'       => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'setting'],
      'code'       => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'expression' => ['type' => 'string', 'null' => false,'length' => '','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_page_bind_action_page1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Page_Bind_Api_Action_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	
	public static function get_mode(){
		return ['setting','code'];
	}

}?>