<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_State_Model extends YZE_Model{
    use Page_Bind_State_Model_Method;
    
    const STATE_TYPE_ACTIVATED = 'activated';
    const STATE_TYPE_DISABLED = 'disabled';
    const STATE_TYPE_HIDDEN = 'hidden';
    const STATE_TYPE_PSEUDO = 'pseudo';
    const STATE_TYPE_CUSTOM = 'custom';
    const TABLE= "page_bind_state";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_State_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 
     * @var string
     */
    const F_UIID = "uiid";
    /**
     * 
     * @var enum
     */
    const F_STATE_TYPE = "state_type";
    /**
     * 
     * @var string
     */
    const F_STATE_NAME = "state_name";
    /**
     * 样式内容
     * @var string
     */
    const F_STYLE = "style";
    /**
     * Selector
     * @var string
     */
    const F_STYLE_ID = "style_id";
    /**
     * 
     * @var string
     */
    const F_EXPRESSION = "expression";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'uiid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'state_type' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> ''],
      'state_name' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'style'      => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'style_id'   => ['type' => 'string', 'null' => true,'length' => '145','default'	=> ''],
      'expression' => ['type' => 'string', 'null' => false,'length' => '','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_category2_page1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Page_Bind_State_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	
	public static function get_state_type(){
		return ['activated','disabled','hidden','pseudo','custom'];
	}

}?>