<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_Data_Model extends YZE_Model{
    use Page_Bind_Data_Model_Method;
    
    const TYPE_STRING = 'string';
    const TYPE_INTEGER = 'integer';
    const TYPE_NUMBER = 'number';
    const TYPE_ARRAY = 'array';
    const TYPE_BOOLEAN = 'boolean';
    const TYPE_OBJECT = 'object';
    const TYPE_NULL = 'null';
    const TYPE_ANY = 'any';
    const TYPE_MAP = 'map';
    const DATA_FROM_PAGE = 'page';
    const DATA_FROM_PATH = 'path';
    const DATA_FROM_QUERY = 'query';
    const ACTION_READONLY = 'ReadOnly';
    const ACTION_WRITEONLY = 'WriteOnly';
    const ACTION_READWRITE = 'ReadWrite';
    const TABLE= "page_bind_data";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_Data_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 
     * @var enum
     */
    const F_TYPE = "type";
    /**
     * 
     * @var string
     */
    const F_NAME = "name";
    /**
     * 
     * @var string
     */
    const F_TITLE = "title";
    /**
     * 
     * @var string
     */
    const F_COMMENT = "comment";
    /**
     * 
     * @var string
     */
    const F_CONTENT = "content";
    /**
     * 
     * @var enum
     */
    const F_DATA_FROM = "data_from";
    /**
     * 
     * @var string
     */
    const F_DEFAULTVALUE = "defaultValue";
    /**
     * 
     * @var integer
     */
    const F_DEPRECATED = "deprecated";
    /**
     * 
     * @var integer
     */
    const F_NULLABLE = "nullable";
    /**
     * 
     * @var integer
     */
    const F_REQUIRED = "required";
    /**
     * 
     * @var integer
     */
    const F_MIN = "min";
    /**
     * 
     * @var integer
     */
    const F_MAX = "max";
    /**
     * 验证模式
     * @var string
     */
    const F_PATTERN = "pattern";
    /**
     * 枚举值列表
     * @var string
     */
    const F_ENUMVALUE = "enumValue";
    /**
     * 样例
     * @var string
     */
    const F_SAMPLE = "sample";
    /**
     * 动作
     * @var enum
     */
    const F_ACTION = "action";
    /**
     * 
     * @var string
     */
    const F_MOCK = "mock";
    /**
     * 
     * @var integer
     */
    const F_INITLENGTH = "initLength";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'type'       => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'string'],
      'name'       => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'title'      => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'comment'    => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'content'    => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'data_from'  => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'page'],
      'defaultValue' => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'deprecated' => ['type' => 'integer', 'null' => false,'length' => '1','default'	=> '0'],
      'nullable'   => ['type' => 'integer', 'null' => false,'length' => '1','default'	=> '0'],
      'required'   => ['type' => 'integer', 'null' => false,'length' => '1','default'	=> '0'],
      'min'        => ['type' => 'integer', 'null' => true,'length' => '','default'	=> ''],
      'max'        => ['type' => 'integer', 'null' => true,'length' => '','default'	=> ''],
      'pattern'    => ['type' => 'string', 'null' => true,'length' => '945','default'	=> ''],
      'enumValue'  => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'sample'     => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'action'     => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'ReadWrite'],
      'mock'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'initLength' => ['type' => 'integer', 'null' => true,'length' => '','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_page_bind_data_page1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Page_Bind_Data_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	
	public static function get_type(){
		return ['string','integer','number','array','boolean','object','null','any','map'];
	}
	public static function get_data_from(){
		return ['page','path','query'];
	}
	public static function get_action(){
		return ['ReadOnly','WriteOnly','ReadWrite'];
	}

}?>