<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_Variable_Model extends YZE_Model{
    use Page_Bind_Variable_Model_Method;
    
    const TABLE= "page_bind_variable";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_Variable_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_FROM_PAGE_ID = "from_page_id";
    /**
     * data_id的来源
     * @var string
     */
    const F_FROM_CLASS = "from_class";
    /**
     * 
     * @var string
     */
    const F_FROM_UUID = "from_uuid";
    /**
     * 
     * @var string
     */
    const F_FROM_EXPRESSION = "from_expression";
    /**
     * 
     * @var integer
     */
    const F_TO_PAGE_ID = "to_page_id";
    /**
     * data_id的来源
     * @var string
     */
    const F_TO_CLASS = "to_class";
    /**
     * Root data uuid
     * @var string
     */
    const F_TO_UUID = "to_uuid";
    /**
     * 
     * @var string
     */
    const F_TO_DATA_ID = "to_data_id";
    /**
     * 
     * @var string
     */
    const F_TO_DATA_PATH = "to_data_path";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'from_page_id' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'from_class' => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'from_uuid'  => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'from_expression' => ['type' => 'string', 'null' => false,'length' => '','default'	=> ''],
      'to_page_id' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'to_class'   => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'to_uuid'    => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'to_data_id' => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'to_data_path' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'from_page_id' => 'fk_page_bind_io_page1_idx',
  'from_class' => 'idx_from',
  'to_page_id' => 'fk_page_bind_variable_page1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'from_page_id' => 
  array (
    'graphql_field' => 'from_page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
  'to_page_id' => 
  array (
    'graphql_field' => 'to_page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $from_page;
	private $to_page;
	
	public function get_from_page($suffix=null){
		if( ! $this->from_page){
			$this->from_page = Page_Model::find_by_id($this->get(self::F_FROM_PAGE_ID), $this->db, $suffix);
		}
		return $this->from_page;
	}

	/**
	 * @return Page_Bind_Variable_Model
	 */
	public function set_from_page(Page_Model $new){
		$this->from_page = $new;
		return $this;
	}

	public function get_to_page($suffix=null){
		if( ! $this->to_page){
			$this->to_page = Page_Model::find_by_id($this->get(self::F_TO_PAGE_ID), $this->db, $suffix);
		}
		return $this->to_page;
	}

	/**
	 * @return Page_Bind_Variable_Model
	 */
	public function set_to_page(Page_Model $new){
		$this->to_page = $new;
		return $this;
	}

	

}?>