<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
use \app\project\Uicomponent_Event_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_Event_Model extends YZE_Model{
    use Page_Bind_Event_Model_Method;
    
    const TABLE= "page_bind_event";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_Event_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 绑定的事件
     * @var string
     */
    const F_EVENT = "event";
    /**
     * 绑定的uiid
     * @var string
     */
    const F_UIID = "uiid";
    /**
     * 
     * @var integer
     */
    const F_UICOMPONENT_EVENT_ID = "uicomponent_event_id";
    /**
     * 
     * @var string
     */
    const F_DESC = "desc";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'event'      => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'uiid'       => ['type' => 'string', 'null' => true,'length' => '445','default'	=> ''],
      'uicomponent_event_id' => ['type' => 'integer', 'null' => true,'length' => '','default'	=> ''],
      'desc'       => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_page_bind_event_page1_idx',
  'uicomponent_event_id' => 'fk_page_bind_event_uicomponent_event1',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
  'uicomponent_event_id' => 
  array (
    'graphql_field' => 'uicomponent_event',
    'target_class' => '\\app\\project\\Uicomponent_Event_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	private $uicomponent_event;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Page_Bind_Event_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	public function get_uicomponent_event($suffix=null){
		if( ! $this->uicomponent_event){
			$this->uicomponent_event = Uicomponent_Event_Model::find_by_id($this->get(self::F_UICOMPONENT_EVENT_ID), $this->db, $suffix);
		}
		return $this->uicomponent_event;
	}

	/**
	 * @return Page_Bind_Event_Model
	 */
	public function set_uicomponent_event(Uicomponent_Event_Model $new){
		$this->uicomponent_event = $new;
		return $this;
	}

	

}?>