<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Page_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Page_Bind_Api_Model extends YZE_Model{
    use Page_Bind_Api_Model_Method;
    
    const REQUESTBODYTYPE_NONE = 'none';
    const REQUESTBODYTYPE_FORM_DATA = 'form-data';
    const REQUESTBODYTYPE_X_WWW_FORM_URLENCODED = 'x-www-form-urlencoded';
    const REQUESTBODYTYPE_JSON = 'json';
    const REQUESTBODYTYPE_XML = 'xml';
    const REQUESTBODYTYPE_RAW = 'raw';
    const REQUESTBODYTYPE_BINARY = 'binary';
    const REQUESTBODYTYPE_GRAPHQL = 'GraphQL';
    const REQUESTBODYTYPE_MSGPACK = 'msgpack';
    const TABLE= "page_bind_api";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Page_Bind_Api_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_PAGE_ID = "page_id";
    /**
     * 
     * @var integer
     */
    const F_WEB_API_ID = "web_api_id";
    /**
     * api名称
     * @var string
     */
    const F_NAME = "name";
    /**
     * api方法
     * @var string
     */
    const F_METHOD = "method";
    /**
     * 请求路径
     * @var string
     */
    const F_PATH = "path";
    /**
     * 
     * @var string
     */
    const F_INPUT = "input";
    /**
     * 
     * @var string
     */
    const F_OUTPUT = "output";
    /**
     * 
     * @var enum
     */
    const F_REQUESTBODYTYPE = "requestBodyType";
    /**
     * 
     * @var integer
     */
    const F_MAJOR = "major";
    /**
     * 
     * @var integer
     */
    const F_MINOR = "minor";
    /**
     * 
     * @var integer
     */
    const F_REVISION = "revision";
    /**
     * 
     * @var integer
     */
    const F_VERSION = "version";
    /**
     * 调用api的对象
     * @var string
     */
    const F_BIND_CLASS = "bind_class";
    /**
     * 
     * @var string
     */
    const F_BIND_UUID = "bind_uuid";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'page_id'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'web_api_id' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'name'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'method'     => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'path'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'input'      => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'output'     => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
      'requestBodyType' => ['type' => 'enum', 'null' => false,'length' => '','default'	=> 'form-data'],
      'major'      => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'minor'      => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'revision'   => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '1'],
      'version'    => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '1'],
      'bind_class' => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'bind_uuid'  => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'page_id' => 'fk_page_bind_api_page1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'page_id' => 
  array (
    'graphql_field' => 'page',
    'target_class' => '\\app\\project\\Page_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $page;
	
	public function get_page($suffix=null){
		if( ! $this->page){
			$this->page = Page_Model::find_by_id($this->get(self::F_PAGE_ID), $this->db, $suffix);
		}
		return $this->page;
	}

	/**
	 * @return Page_Bind_Api_Model
	 */
	public function set_page(Page_Model $new){
		$this->page = $new;
		return $this;
	}

	
	public static function get_requestBodyType(){
		return ['none','form-data','x-www-form-urlencoded','json','xml','raw','binary','GraphQL','msgpack'];
	}

}?>