<?php
namespace app\project;
use \yangzie\YZE_Model;
use \yangzie\YZE_SQL;
use \yangzie\YZE_DBAException;
use \yangzie\YZE_DBAImpl;
use \app\project\Project_Model;
/** 
 * DO NOT EDIT THIS FILE
 * @package project
 */
class Project_Setting_Model extends YZE_Model{
    use Project_Setting_Model_Method;
    
    const TABLE= "project_setting";
    const MODULE_NAME = "project";
    const KEY_NAME = "id";
	const UUID_NAME = "uuid";
    const CLASS_NAME = 'app\project\Project_Setting_Model';
    /**
     * @see YZE_Model::$encrypt_columns 
     */
    public $encrypt_columns = array();
    
    /**
     * 
     * @var integer
     */
    const F_ID = "id";
    /**
     * 
     * @var date
     */
    const F_CREATED_ON = "created_on";
    /**
     * 
     * @var date
     */
    const F_MODIFIED_ON = "modified_on";
    /**
     * 
     * @var integer
     */
    const F_IS_DELETED = "is_deleted";
    /**
     * 
     * @var string
     */
    const F_UUID = "uuid";
    /**
     * 
     * @var integer
     */
    const F_PROJECT_ID = "project_id";
    /**
     * 
     * @var string
     */
    const F_NAME = "name";
    /**
     * 
     * @var string
     */
    const F_VALUE = "value";
    public static $columns = [
    'id'         => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'created_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'modified_on' => ['type' => 'date', 'null' => false,'length' => '','default'	=> 'CURRENT_TIMESTAMP'],
      'is_deleted' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> '0'],
      'uuid'       => ['type' => 'string', 'null' => false,'length' => '45','default'	=> ''],
      'project_id' => ['type' => 'integer', 'null' => false,'length' => '','default'	=> ''],
      'name'       => ['type' => 'string', 'null' => true,'length' => '45','default'	=> ''],
      'value'      => ['type' => 'string', 'null' => true,'length' => '','default'	=> ''],
    ];
    /**
     * @see YZE_Model::$unique_key
     */
    protected $unique_key = array (
  'id' => 'PRIMARY',
  'project_id' => 'fk_project_setting_project1_idx',
);

    /**
     * @see YZE_Model::$relation_column
     */
    protected $relation_column = array (
  'project_id' => 
  array (
    'graphql_field' => 'project',
    'target_class' => '\\app\\project\\Project_Model',
    'target_column' => 'id',
  ),
);
    		
    
	private $project;
	
	public function get_project($suffix=null){
		if( ! $this->project){
			$this->project = Project_Model::find_by_id($this->get(self::F_PROJECT_ID), $this->db, $suffix);
		}
		return $this->project;
	}

	/**
	 * @return Project_Setting_Model
	 */
	public function set_project(Project_Model $new){
		$this->project = $new;
		return $this;
	}

	

}?>